# Form implementation generated from reading ui file 'layout.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(800, 600)
        Dialog.setStyleSheet("background-color: cadetblue; color: black;")
        self.centralwidget = QtWidgets.QWidget(parent=Dialog)
        self.centralwidget.setGeometry(QtCore.QRect(0, 0, 801, 601))
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setStyleSheet("color: antiquewhite;\n"
"font-size: 24px;")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.txtKlucz = QtWidgets.QPlainTextEdit(parent=self.centralwidget)
        self.txtKlucz.setMaximumSize(QtCore.QSize(16777215, 20))
        self.txtKlucz.setStyleSheet("background-color: white; margin: 0 auto;")
        self.txtKlucz.setObjectName("txtKlucz")
        self.verticalLayout.addWidget(self.txtKlucz)
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setStyleSheet("color: antiquewhite;\n"
"font-size: 24px;")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.txtTekst = QtWidgets.QPlainTextEdit(parent=self.centralwidget)
        self.txtTekst.setAutoFillBackground(False)
        self.txtTekst.setStyleSheet("background-color: white;")
        self.txtTekst.setPlainText("")
        self.txtTekst.setObjectName("txtTekst")
        self.verticalLayout.addWidget(self.txtTekst)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.btnDodaj = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnDodaj.setStyleSheet("background-color: lightblue;")
        self.btnDodaj.setObjectName("btnDodaj")
        self.horizontalLayout.addWidget(self.btnDodaj)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label_3.setStyleSheet("color: antiquewhite;\n"
"font-size: 24px;")
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.lblZaszyfrowany = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblZaszyfrowany.setStyleSheet("color: aliceblue;\n"
"font-size: 18px;\n"
"border: 5px solid antiquewhite;\n"
"border-radius: 15px;\n"
"padding: 10px;")
        self.lblZaszyfrowany.setText("")
        self.lblZaszyfrowany.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.lblZaszyfrowany.setObjectName("lblZaszyfrowany")
        self.verticalLayout_2.addWidget(self.lblZaszyfrowany)
        self.btnZapisz = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnZapisz.setStyleSheet("background-color: lightblue;")
        self.btnZapisz.setObjectName("btnZapisz")
        self.verticalLayout_2.addWidget(self.btnZapisz)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Szyfrowanie. Filip Pawłowski 5Tp"))
        self.label.setText(_translate("Dialog", "Podaj wartość klucza"))
        self.label_2.setText(_translate("Dialog", "Podaj tekst"))
        self.btnDodaj.setText(_translate("Dialog", "Zaszyfruj"))
        self.label_3.setText(_translate("Dialog", "Tekst zaszyfrowany"))
        self.btnZapisz.setText(_translate("Dialog", "Zapisz szyfr w pliku"))
